### ISSUE TITLE
Defining triggers

### ISSUE THREAD

**Issue by dnordberg** [inv2004/ttop#28]
No documentation on defining the triggers.

Or are they preset to something? Would be good to know.

**Comment by inv2004** [comment]
Hm, let me think how to improve readme about it.

Trigger is any external script or command which receives text from ttop into stdin
I think that the most simple trigger for debug needs is:
```toml
[[trigger]]
on_info = true   # to not wait for any alert
cmd = 
cmd = 'cat > /tmp/ttop.txt'
```

```bash
> ttop -s   # the same thing ttop.timer does
> cat /tmp/ttop.txt
```

where are also some additional env variables you can use from the cmd: `TTOP_ALERT`, `TTOP_INFO`, `TTOP_TYPE`, `TTOP_HOST`

In readme you can find examples how to send email or telegram notifications, but you can can write your own
